<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MD0BEV7" failures="1" tests="1" name="CaseManagement.CaseManagement_TC" time="0.001" errors="0" timestamp="16 Jan 2025 11:55:39 GMT">
  <testcase classname="CaseManagement.CaseManagement_TC" name="verifyCasesComponent" time="0.001">
    <failure message="
Can&#039;t invoke public void CaseManagement.CaseManagement_TC.verifyCasesComponent() throws java.lang.InterruptedException: either make it static or add a no-args constructor to your class" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Can't invoke public void CaseManagement.CaseManagement_TC.verifyCasesComponent() throws java.lang.InterruptedException: either make it static or add a no-args constructor to your class
	at org.testng.internal.Utils.checkInstanceOrStatic(Utils.java:803)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:36)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyCasesComponent -->
</testsuite> <!-- CaseManagement.CaseManagement_TC -->
