<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MD0BEV7" failures="0" tests="3" name="CaseManagement.ValidationCaseViewPageNavigation" time="35.704" errors="1" timestamp="16 Jan 2025 15:13:33 GMT">
  <testcase classname="CaseManagement.ValidationCaseViewPageNavigation" name="ValidateUserOnCasesModuleTest" time="7.525"/>
  <testcase classname="CaseManagement.ValidationCaseViewPageNavigation" name="navigateToApplicationTest" time="11.221"/>
  <testcase classname="CaseManagement.ValidationCaseViewPageNavigation" name="ValidateUserOnCasesViewPageTest" time="16.958">
    <error message="text did not match the expected value. expected [CASE-00096] but found [CM-00467]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: text did not match the expected value. expected [CASE-00096] but found [CM-00467]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at CaseManagement.ValidationCaseViewPageNavigation.ValidateUserOnCasesViewPageTest(ValidationCaseViewPageNavigation.java:67)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- ValidateUserOnCasesViewPageTest -->
</testsuite> <!-- CaseManagement.ValidationCaseViewPageNavigation -->
